---
stages:
  - lint
  - build
  - publish
  - mirror

# Match GitLab executors Docker version and directly use the Docker socket
# The Docker daemon is already configured, experimental features are enabled
# The following environment variables are already set:
# - BUILDKIT_PROGRESS
# - DOCKER_DRIVER
# - DOCKER_VERSION
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-socket-binding
.image_template__docker:
  # https://gitlab.com/tezos/docker-images/ci-docker
  image: "${CI_REGISTRY}/tezos/docker-images/ci-docker:v1.4.0"
  before_script:
    # Credentials for Docker registries
    - ./scripts/docker_registry_auth.sh

# Template used by all Docker image build jobs
# Variables needs to be set properly
.build-template: &build-definition
  stage: build
  extends:
    - .image_template__docker
  variables:
    ARCH: ""                     # Used by `scripts/build-libusb-hidapi.sh` to build static packages
    TARGETARCH: ""               # Docker build argument for architecture specific instructions
    DOCKER_IMAGE_TAG_SUFFIX: ""
  script:
    # Build docker images
    - ./scripts/create_docker_image.sh "${CI_REGISTRY_IMAGE}" "${DOCKER_IMAGE_TAG_SUFFIX}" "${ARCH}" "${TARGETARCH}"
    # Push docker images
    - ./scripts/docker_push_all.sh "${CI_REGISTRY_IMAGE}" "${DOCKER_IMAGE_TAG_SUFFIX}"

# Dockerfile linter
hadolint:
  image: hadolint/hadolint:v2.10.0-debian
  stage: lint
  script:
    - hadolint *Dockerfile

# POSIX shell scripts linter
shellcheck:
  image: koalaman/shellcheck-alpine:v0.8.0
  stage: lint
  script:
    - shellcheck -x scripts/*.sh

# Build docker images for x86_64/amd64
build-amd64:
  <<: *build-definition
  variables:
    ARCH: "x86_64"
    TARGETARCH: "amd64"
    DOCKER_IMAGE_TAG_SUFFIX: "--${TARGETARCH}--${CI_COMMIT_SHA}"
  only:
    - //@tezos/opam-repository
    - //@nomadic-labs/opam-repository

# Build docker images for arm64/v8
# Only on Nomadic Labs' repositories and arm64 runners
build-arm64:
  <<: *build-definition
  variables:
    ARCH: "aarch64"
    TARGETARCH: "arm64"
    DOCKER_IMAGE_TAG_SUFFIX: "--${TARGETARCH}--${CI_COMMIT_SHA}"
  only:
    - //@tezos/opam-repository
    - //@nomadic-labs/opam-repository
  tags:
    - arm64

# Merge manifests from jobs build-amd64 and build-arm64
# Only on Nomadic Labs' repositories
# (Forks don't have the capacity to build arm64 images and thus they don't have the
# capacity to merge the manifest either)
manifest:
  stage: publish
  extends:
    - .image_template__docker
  script:
    - ./scripts/docker_merge_manifests.sh "${CI_REGISTRY_IMAGE}"
  only:
    - //@tezos/opam-repository
    - //@nomadic-labs/opam-repository

# Mirror Docker image from Gitlab container registry @GCP to private ECR @AWS,
# closer to GitLab runners/executors. Requires environment variables to be set
# with AWS credentials and AWS_ECR.
mirror:
  stage: mirror
  extends:
    - .image_template__docker
  variables:
    AWS_ECR_IMAGE: "${AWS_ECR}/${CI_PROJECT_PATH}"
  script:
    - ./scripts/mirror_to_ecr.sh "${CI_REGISTRY_IMAGE}" "${AWS_ECR_IMAGE}"
  only:
    variables:
      # Only available on protected branches @nomadic-labs/opam-repository
      - $AWS_ACCESS_KEY_ID && $AWS_SECRET_ACCESS_KEY && $AWS_ECR

# Duplicated job to allow forks to build x86_64/amd64 images
build:
  <<: *build-definition
  image: docker:20
  services:
    - name: docker:20-dind
      command: ["--experimental"]
  variables:
    ARCH: "x86_64"
    # this variable is empty as we don't want to merge any manifest
    DOCKER_IMAGE_TAG_SUFFIX: ""
  except:
    - //@tezos/opam-repository
    - //@nomadic-labs/opam-repository
