---
default:
  interruptible: true

stages:
  - lint
  - build
  - publish
  - mirror

.rules_template__nomadic:
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "tezos" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - if: '$CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - when: never  # default

.rules_template__fork:
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "nomadic-labs" && $CI_PROJECT_NAMESPACE != "tezos"'
      when: on_success
    - when: never  # default

# Match GitLab executors Docker version and directly use the Docker socket
# The Docker daemon is already configured, experimental features are enabled
# The following environment variables are already set:
# - BUILDKIT_PROGRESS
# - DOCKER_DRIVER
# - DOCKER_VERSION
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-socket-binding
.image_template__docker:
  # https://gitlab.com/tezos/docker-images/ci-docker
  image: "${CI_REGISTRY}/tezos/docker-images/ci-docker:v1.7.0"
  before_script:
    # Credentials for Docker registries
    - ./scripts/docker_registry_auth.sh

# Template used by all Docker image build jobs
# Variables needs to be set properly
.build_template:
  stage: build
  extends:
    - .image_template__docker
  variables:
    TARGETARCH: ""               # Docker build argument for architecture specific instructions
    DOCKER_IMAGE_TAG_SUFFIX: ""
  script:
    - . ./scripts/version.sh
    # Build docker images
    - ./scripts/create_docker_image.sh "${CI_REGISTRY_IMAGE}" "${DOCKER_IMAGE_TAG_SUFFIX}" "${TARGETARCH}"
    # Verify we packed expected software versions
    - ./scripts/check_versions.sh "${CI_REGISTRY_IMAGE}" "${DOCKER_IMAGE_TAG_SUFFIX}"
    # Push docker images
    - ./scripts/docker_push_all.sh "${CI_REGISTRY_IMAGE}" "${DOCKER_IMAGE_TAG_SUFFIX}"

# Dockerfile linter
hadolint:
  extends:
    - .rules_template__nomadic
  image: hadolint/hadolint:v2.10.0-debian
  stage: lint
  script:
    - hadolint *Dockerfile

# POSIX shell scripts linter
shellcheck:
  extends:
    - .rules_template__nomadic
  image: koalaman/shellcheck-alpine:v0.8.0
  stage: lint
  script:
    - shellcheck -x scripts/*.sh

# Build docker images for x86_64/amd64
build-amd64:
  extends:
    - .build_template
    - .rules_template__nomadic
  variables:
    TARGETARCH: "amd64"
    DOCKER_IMAGE_TAG_SUFFIX: "--${TARGETARCH}--${CI_COMMIT_SHA}"

# Build docker images for arm64/v8
# Only on Nomadic Labs' repositories and arm64 runners
build-arm64:
  extends:
    - .build_template
    - .rules_template__nomadic
  variables:
    TARGETARCH: "arm64"
    DOCKER_IMAGE_TAG_SUFFIX: "--${TARGETARCH}--${CI_COMMIT_SHA}"
  tags: [arm64]

# Merge manifests from jobs build-amd64 and build-arm64
# Only on Nomadic Labs' repositories
# (Forks don't have the capacity to build arm64 images and thus they don't have the
# capacity to merge the manifest either)
manifest:
  stage: publish
  extends:
    - .image_template__docker
    - .rules_template__nomadic
  script:
    - ./scripts/docker_merge_manifests.sh "${CI_REGISTRY_IMAGE}"

# Mirror Docker image from Gitlab container registry @GCP to private ECR @AWS, closer to
# GitLab runners/executors. Requires the following environment variables to be set:
# - AWS_ECR
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
mirror:
  stage: mirror
  extends:
    - .image_template__docker
    - .rules_template__nomadic
  variables:
    AWS_ECR_IMAGE: "${AWS_ECR}/${CI_PROJECT_PATH}"
  script:
    - ./scripts/mirror_to_ecr.sh "${CI_REGISTRY_IMAGE}" "${AWS_ECR_IMAGE}"

# Duplicated job to allow forks to build images using defaults
build:
  extends:
    - .build_template
    - .rules_template__fork
  services:
    - name: docker:20-dind
      command: ["--experimental"]
