---

workflow:
  name: "[$PIPELINE_TYPE] $CI_COMMIT_TITLE"
  rules:
    # Use merge request pipelines
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        PIPELINE_TYPE: 'mr'
    # Inhibit double pipelines
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    # Allow branch pipelines on non-master branches if there is no merge request.
    # No need to run branch pipelines on master: images are built and
    # pushed by the merge request pipelines.
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: always
      variables:
        PIPELINE_TYPE: 'branch'
    - when: never

default:
  interruptible: true

stages:
  - lint
  - build
  - publish
  - mirror

# Match GitLab executors Docker version and directly use the Docker socket
# The Docker daemon is already configured, experimental features are enabled
# The following environment variables are already set:
# - BUILDKIT_PROGRESS
# - DOCKER_DRIVER
# - DOCKER_VERSION
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-socket-binding
.image_template__docker:
  # https://gitlab.com/tezos/docker-images/ci-docker
  image: "${CI_REGISTRY}/tezos/docker-images/ci-docker:v1.7.0"
  before_script:
    # Credentials for Docker registries
    - ./scripts/docker_registry_auth.sh

.rules__tezos_namespace:
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "tezos"'

.rules__not_tezos_namespace:
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "tezos"'

.rules__protected:
  rules:
    - if: '$AWS_ACCESS_KEY_ID && $AWS_SECRET_ACCESS_KEY && $AWS_ECR'

# Template used by all Docker image build jobs
# Variables needs to be set properly
.build-template:
  stage: build
  extends:
    - .image_template__docker
  variables:
    TARGETARCH: ""               # Docker build argument for architecture specific instructions
    DOCKER_IMAGE_TAG_SUFFIX: ""
    DOCKER_IMAGE_FAMILY: ""
  script:
    - . ./scripts/version.sh
    # Build docker images
    - ./scripts/create_docker_image.sh "${CI_REGISTRY_IMAGE}" "${DOCKER_IMAGE_TAG_SUFFIX}" "${TARGETARCH}" "${DOCKER_IMAGE_FAMILY}"
    # Verify we packed expected software versions
    - ./scripts/check_versions.sh "${CI_REGISTRY_IMAGE}" "${DOCKER_IMAGE_TAG_SUFFIX}" "${DOCKER_IMAGE_FAMILY}"
    # Push docker images
    - ./scripts/docker_push_all.sh "${CI_REGISTRY_IMAGE}" "${DOCKER_IMAGE_TAG_SUFFIX}" "${DOCKER_IMAGE_FAMILY}"

# Dockerfile linter
hadolint:
  image: hadolint/hadolint:v2.10.0-debian
  stage: lint
  script:
    - hadolint *Dockerfile

# POSIX shell scripts linter
shellcheck:
  image: koalaman/shellcheck-alpine:v0.8.0
  stage: lint
  script:
    - shellcheck -x scripts/*.sh

# Build runtime family docker images for x86_64/amd64
build-runtime-amd64:
  extends:
    - .build-template
    - .rules__tezos_namespace
  variables:
    TARGETARCH: "amd64"
    DOCKER_IMAGE_TAG_SUFFIX: "--${TARGETARCH}--${CI_COMMIT_SHA}"
    DOCKER_IMAGE_FAMILY: "runtime"

# Build runtime family Docker images for arm64/v8
# Only on Nomadic Labs' repositories and arm64 runners
build-runtime-arm64:
  extends:
    - .build-template
    - .rules__tezos_namespace
  variables:
    TARGETARCH: "arm64"
    DOCKER_IMAGE_TAG_SUFFIX: "--${TARGETARCH}--${CI_COMMIT_SHA}"
    DOCKER_IMAGE_FAMILY: "runtime"
  tags:
    - arm64

# Build rust-toolchain family Docker image for x86_64/amd64
build-rust-toolchain:
  extends:
    - .build-template
    - .rules__tezos_namespace
  variables:
    TARGETARCH: ""
    DOCKER_IMAGE_TAG_SUFFIX: "--${CI_COMMIT_SHA}"
    DOCKER_IMAGE_FAMILY: "rust-toolchain"

# Merge manifests from jobs build-runtime-amd64 and build-runtime-arm64
# Only on Nomadic Labs' repositories
# (Forks don't have the capacity to build arm64 images and thus they don't have the
# capacity to merge the manifest either)
merge-manifests-runtime:
  stage: publish
  extends:
    - .image_template__docker
    - .rules__tezos_namespace
  script:
    - ./scripts/docker_merge_manifests.sh "${CI_REGISTRY_IMAGE}"

# Mirror Docker image from all families from Gitlab container registry @GCP to private ECR @AWS,
# closer to GitLab runners/executors. Requires environment variables to be set
# with AWS credentials and AWS_ECR.
mirror:
  stage: mirror
  extends:
    - .image_template__docker
    - .rules__protected
  variables:
    AWS_ECR_IMAGE: "${AWS_ECR}/${CI_PROJECT_PATH}"
  script:
    - ./scripts/mirror_to_ecr.sh "${CI_REGISTRY_IMAGE}" "${AWS_ECR_IMAGE}" all

# Duplicated job to allow forks to build x86_64/amd64 images
build:
  extends:
    - .build-template
    - .rules__not_tezos_namespace
  services:
    - name: docker:20-dind
      command: ["--experimental"]
  variables:
    # this variable is empty as we don't want to merge any manifest
    DOCKER_IMAGE_TAG_SUFFIX: ""
    DOCKER_IMAGE_FAMILY: "all"
